server:
  port: 8080
  servlet:
    contextPath:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: strict

spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 4
      maximum-pool-size: 8

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 1s
      password: ${REDIS_PASSWORD}

  session:
    timeout: 30m
    redis:
      flush-mode: on-save

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

oauth2:
  client:
    registration:
      kakao:
        url: ${KAKAO_AUTH_URL}
        client_id: ${KAKAO_CLIENT_ID} # REST API

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: info

decorator:
  datasource:
    p6spy:
      enable-logging: false
