server:
  port: 8080
  servlet:
    contextPath:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false
        same-site: none
  tomcat:
    threads:
      max: 300          # 최대 쓰레드 수 (기본: 200)
      min-spare: 300      # 최소 유지 쓰레드 수 (기본: 10)
    mbeanregistry:
      enabled: true
  url: ${DEV_SERVER_URL}

spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      minimum-idle: 80
      maximum-pool-size: 80

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 1s
      password: ${REDIS_PASSWORD}

    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=${MONGODB_AUTH_SOURCE}
      auto-index-creation: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092

  session:
    timeout: 30m
    redis:
      flush-mode: on-save

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ${AWS_REGION}

springdoc:
  override-with-generic-response: false

oauth2:
  client:
    registration:
      kakao:
        url: ${KAKAO_AUTH_URL}
        client_id: ${KAKAO_CLIENT_ID} # REST API

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image-preview:generateContent

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: baro-server
    distribution:
      percentiles:
        http.server.requests: 0.5,0.9,0.99
      percentiles-histogram:
        http.server.requests: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: info

app:
  async:
    executor:
      core-pool-size: 8
      max-pool-size: 16
      queue-capacity: 300
      keep-alive-seconds: 60
      thread-name-prefix: "event-async-"

decorator:
  datasource:
    p6spy:
      enable-logging: false
